const data = {
    products: [
        {
            _id: '1' ,
            name: 'Anastasia',
            slug: 'gold-hoops-anastasia',
            category: 'Earrings',
            image:'/earrings/gold-hoop-anastasia.jpg',
            price: 60,
            countInStock: 100,
            rating: 4.5,
            numReviews: 15,
            description: 'Gold Earrings'
        },
        {
            _id: '2', 
            name: 'Daihana',
            slug: 'gold-hoops-daihana',
            category: 'Earrings',
            image:'/earrings/gold-hoop-daihana.jpg',
            price: 55,
            countInStock: 60,
            rating: 4.0,
            numReviews: 10,
            description: 'Gold Earrings'
        },
        {
            _id: '3', 
            name: 'Julia',
            slug: 'gold-hoops-julia',
            category: 'Earrings',
            image:'/earrings/gold-hoop-julia.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.6,
            numReviews: 13,
            description: 'Gold Earrings'
        },
        {
            _id: '4', 
            name: 'Mathilde',
            slug: 'gold-hoops-mathilde',
            category: 'Earrings',
            image:'/earrings/gold-hoop-mathilde.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Earrings'
        },
        {
            _id: '5', 
            name: 'Kateryna',
            slug: 'pearl-statement-camila',
            category: 'Earrings',
            image:'/earrings/pearl-statement-kateryna.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Pearl Statement'
        },
        {
            _id: '6', 
            name: 'Leslie',
            slug: 'gold-bracelet-leslie',
            category: 'Bracelets',
            image:'/bracelets/gold-bracelet-leslie.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '7', 
            name: 'Marie',
            slug: 'gold-bracelet-marie',
            category: 'Bracelets',
            image:'/bracelets/gold-bracelet-marie.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '8', 
            name: 'Sandi',
            slug: 'gold-bracelet-sandi',
            category: 'Bracelets',
            image:'/bracelets/gold-bracelet-sandi.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '9', 
            name: 'Shelia',
            slug: 'gold-bracelet-Shelia',
            category: 'Bracelets',
            image:'/bracelets/gold-bracelet-shelia.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '10', 
            name: 'Olivia',
            slug: 'gold-bracelet-olivia',
            category: 'Bracelets',
            image:'/bracelets/pearl-bracelet-olivia.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '11', 
            name: 'Robin',
            slug: 'gold-bracelet-robin',
            category: 'Bracelets',
            image:'/bracelets/sliver-bracelet-robin.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Bracelet'
        },
        {
            _id: '12', 
            name: 'Eliza',
            slug: 'gold-bracelet-eliza',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-eliza.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '13', 
            name: 'Grace',
            slug: 'gold-bracelet-Grace',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-grace.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '14', 
            name: 'Harper',
            slug: 'gold-bracelet-harper',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-harper.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '15', 
            name: 'Imani',
            slug: 'gold-bracelet-imani',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-imani.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '16', 
            name: 'Jasmin',
            slug: 'gold-bracelet-jasmin',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-jasmin.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '17', 
            name: 'Venus',
            slug: 'gold-bracelet-venus',
            category: 'Necklaces',
            image:'/necklaces/gold-necklace-venus.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Necklace'
        },
        {
            _id: '18', 
            name: 'Cassie',
            slug: 'gold-ring-cassie',
            category: 'Necklaces',
            image:'/rings/gold-ring-cassie.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
        {
            _id: '19', 
            name: 'Leilani',
            slug: 'gold-ring-leilani',
            category: 'Necklaces',
            image:'/rings/gold-ring-leilani.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
        {
            _id: '20', 
            name: 'Melanie',
            slug: 'gold-ring-melanie',
            category: 'Necklaces',
            image:'/rings/gold-ring-melanie.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
        {
            _id: '21', 
            name: 'Millie',
            slug: 'gold-ring-millie',
            category: 'Necklaces',
            image:'/rings/gold-ring-millie.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
        {
            _id: '22', 
            name: 'Saint',
            slug: 'gold-ring-saint',
            category: 'Necklaces',
            image:'/rings/gold-ring-saint.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
        {
            _id: '23', 
            name: 'Victoria',
            slug: 'gold-ring-victoria',
            category: 'Necklaces',
            image:'/rings/gold-ring-victoria.jpg',
            price: 55,
            countInStock: 100,
            rating: 4.1,
            numReviews: 10,
            description: 'Gold Ring'
        },
    ]
}
export default data